### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/dino-kennel#11]
https://colors.lol/compulsive

```css
@import url('https://fonts.googleapis.com/css2?family=Orbitron&family=Roboto+Slab:wght@100;400&display=swap');

body {
    font-family: 'Orbitron', sans-serif;
    font-family: 'Roboto Slab', serif;
}
```
